version: "3.8"
services:
  db:
    image : "mongo:4.0.4"
    container_name: mongodb
    volumes:
      - db_vol:/data/db
    ports:
      - "27018:27017"
    networks:
      - db_net
  backend:
    image: "backend:1.0.1"
    build:
      context: server/
      dockerfile: dev.dockerfile
    volumes:
        - ./server:/app
        - backend_node_modules:/dependencies/node_modules
        - backend_node_modules:/app/node_modules:ro
    container_name: backend
    command: ["yarn", "start-debug"]
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - db_net
    depends_on:
      - db
  frontend:
    image: "frontend:0.1.0"
    volumes:
       - ./client:/app
       - frontend_node_modules:/dependencies/node_modules
       - frontend_node_modules:/app/node_modules:ro
    build:
      context: client/
      dockerfile: dev.dockerfile
    container_name: frontend
    command: ["yarn", "start"]
    ports:
      - "8000:8000"
    depends_on:
      - backend
networks:
  db_net:
volumes:
  db_vol:
  frontend_node_modules:
  backend_node_modules:
