version: '3.8'
services:
  db:
    image: "mongo:4.0.4"
    volumes:
      - movies_db:/var/lib/postgresql/data
    networks:
      - db-network

  cache_db:
    image : "redis:6.2.6"
    networks:
      - cache_db_net

  frontend:
    image: ${FRONTEND_IMAGE}
    labels:
      - 'traefik.http.routers.movie-app-frontend.rule=Host("portal.${url}")'
      - "traefik.http.routers.movie-app-frontend.entrypoints=web"
      - "traefik.http.routers.movie-app-frontend.middlewares=ratelimit-infra, traefik-compress"
      - "traefik.http.services.movie-app-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-net"
      - "traefik.enable=true" 
    networks:
      - traefik-net

  backend:
    image: ${BACKEND_IMAGE}
    labels:
      - 'traefik.http.routers.movie-app-backend.rule=(Host("portal.${url}") && PathPrefix("/api"))'
      - "traefik.http.routers.movie-app-backend.middlewares=api-middleware, ratelimit-infra, traefik-compress"
      - "traefik.http.routers.movie-app-backend.entrypoints=web"
      - "traefik.http.services.movie-app-backend.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-net"
      - "traefik.enable=true" 
    networks:
      - traefik-net
      - db-network
      - cache_db_net

networks:
  db-network:
    external: false
  cache_db_net:
    external: false
  traefik-net:
    external: true

volumes:
  movies_db:
    external: false
