version: '3.8'
services:
  db:
    image: "mongo:4.0.4"
    volumes:
      - movies_db:/var/lib/postgresql/data
    networks:
      - db-network
  frontend:
    image: abdullahsensory/movieapp-frontend:1.0.0
  backend:
    image: abdullahsensory/movieapp-backend:1.0.0
    networks:
      - db-network
networks:
  db-network:
    external: false
volumes:
  movies_db:
    external: false
