version: '3.8'
services:
  db:
    image: "mongo:4.0.4"
    volumes:
      - movies_db:/var/lib/postgresql/data
    networks:
      - db-network
  frontend:
    image: abdullahsensory/movieapp-frontend:1.0.0
    labels:
      - 'traefik.http.routers.movie-app-frontend.rule=Host("portal.${url}")'
      - "traefik.http.routers.movie-app-frontend.entrypoints=web"
      - "traefik.http.services.movie-app-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-net"
      - "traefik.enable=true" 
    networks:
      - traefik-net
  backend:
    image: abdullahsensory/movieapp-backend:1.0.0
    labels:
      - 'traefik.http.routers.movie-app-backend.rule=(Host("portal.${url}") && PathPrefix("/api"))'
      - "traefik.http.routers.movie-app-backend.middlewares=api-middleware"
      - "traefik.http.routers.movie-app-backend.entrypoints=web"
      - "traefik.http.services.movie-app-backend.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-net"
      - "traefik.enable=true" 
    networks:
      - db-network
networks:
  db-network:
    external: false
  traefik-net:
    external: true
volumes:
  movies_db:
    external: false
